<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fluid_language_selector"
 *
 * Auto generated by Extension Builder 2013-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Language Selector',
	'description' => 'A language selector implemented in fluid',
	'category' => 'plugin',
	'author' => 'Anno v. Heimburg',
	'author_email' => 'anno@vonheimburg.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'extbase_core_tables' => '0.0.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>